create table if not exists public.water_levels (
  id bigint generated by default as identity primary key,
  station_code text not null,
  water_level numeric(8, 3) not null,
  flow_rate numeric(12, 3),
  recorded_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint water_levels_station_recorded_unique unique (station_code, recorded_at)
);

create index if not exists water_levels_station_recorded_idx
  on public.water_levels (station_code, recorded_at desc);

alter table public.water_levels enable row level security;

-- เปิดให้อ่านข้อมูลกราฟได้ แต่ไม่อนุญาตให้ browser เขียนข้อมูลโดยตรง
create policy "Public can read water levels"
  on public.water_levels for select
  to anon, authenticated
  using (true);

-- การบันทึกข้อมูลควรทำผ่าน Netlify Function ที่ใช้ SUPABASE_SERVICE_ROLE_KEY เท่านั้น
