[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/water-level"
  to = "/.netlify/functions/mae-khan-water-level"
  status = 200

[[headers]]
  for = "/data/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=300"
